// Package storage is the file storage layer: upload/download endpoints
// backed by a pluggable Backend for the raw bytes and a `files` table
// (see internal/db/migrations/0005_storage.sql) for metadata. Row-level
// ownership follows the same convention as internal/restapi's owner_id
// columns — every file belongs to the subject that uploaded it, and only
// they can list, read, or delete it — but files live outside auto-REST
// entirely (see registry.go's reservedTables) since uploads/downloads
// need multipart and raw-byte handling generic JSON CRUD doesn't do.
package storage

import (
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
)

// Backend stores and retrieves raw file bytes by key, decoupled from the
// files table's metadata so a future non-local backend (S3, etc.) can
// slot in without changing Server or the HTTP layer.
type Backend interface {
	Put(ctx context.Context, key string, r io.Reader) (size int64, err error)
	Open(ctx context.Context, key string) (io.ReadCloser, error)
	Delete(ctx context.Context, key string) error
}

// LocalBackend stores each file as one flat file under Dir, named by its
// key (a UUID generated by Server.handleUpload, never user input, so
// there's no path-traversal concern in the key itself). Fine at
// small-VPS scale; a deployment with an enormous number of files might
// eventually want key-prefix sharding across subdirectories to keep any
// one directory listing small — not needed yet.
type LocalBackend struct {
	Dir string
}

// NewLocalBackend creates Dir (including parents) if it doesn't exist.
func NewLocalBackend(dir string) (*LocalBackend, error) {
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return nil, fmt.Errorf("create storage dir: %w", err)
	}
	return &LocalBackend{Dir: dir}, nil
}

func (b *LocalBackend) path(key string) string {
	return filepath.Join(b.Dir, key)
}

func (b *LocalBackend) Put(_ context.Context, key string, r io.Reader) (int64, error) {
	f, err := os.OpenFile(b.path(key), os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0o600)
	if err != nil {
		return 0, fmt.Errorf("create file: %w", err)
	}
	defer f.Close()

	n, err := io.Copy(f, r)
	if err != nil {
		_ = os.Remove(b.path(key))
		return 0, fmt.Errorf("write file: %w", err)
	}
	return n, nil
}

func (b *LocalBackend) Open(_ context.Context, key string) (io.ReadCloser, error) {
	return os.Open(b.path(key))
}

func (b *LocalBackend) Delete(_ context.Context, key string) error {
	err := os.Remove(b.path(key))
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	return nil
}
