package main

import "strings"

// skillRelPath is where maubase init scaffolds the agent-context skill,
// relative to the project directory — see spec/project-init.md INIT-07.
// Nested under .claude/skills/ (Claude Code's own project-skill
// discovery path) rather than a root-level AGENTS.md/CLAUDE.md: those
// belong to whatever app gets built in this project, and maubase writing
// into a file it doesn't own risks clobbering it in an existing repo. A
// namespaced skill never competes for that.
const skillRelPath = ".claude/skills/maubase/SKILL.md"

// renderSkill fills skillTemplate with the maubase version generating
// it. Everything in the template is static — maubase's own stable
// concepts and commands, not this project's dynamic state (its actual
// schema, migration status, configured env vars), which goes stale the
// moment someone adds a table and belongs to a live command
// ("maubase migrate status", ".env") instead of a generated file.
func renderSkill() string {
	return strings.ReplaceAll(skillTemplate, "{{VERSION}}", currentModuleVersion())
}

// skillTemplate is wrapped in a <!-- maubase:begin/end --> managed
// block so a future "refresh this after upgrading" command (see #161)
// can replace just this content without touching anything a person
// appends below the closing marker.
const skillTemplate = `---
name: maubase
description: Use when working on a project backed by maubase (a self-hosted auth/database/storage/realtime backend) — adding endpoints, changing schema, or touching auth/migrations/access rules in this project.
---

<!-- maubase:begin {{VERSION}} -->
# maubase

This project's backend is maubase — a single self-hosted Go binary
providing auth, a database with an automatic REST API, file storage,
realtime subscriptions, and OAuth 2.1, all backed by one SQLite file.
One ` + "`maubase serve`" + ` process serves exactly this project — there's no
multi-tenant mode; running another project means running another,
separate process with its own ` + "`MAUBASE_ADDR`" + `/` + "`MAUBASE_DB_PATH`" + `.

Generated by ` + "`maubase init`" + ` for **{{VERSION}}**. If ` + "`maubase version`" + `
reports something different, treat specifics below as possibly stale —
prefer ` + "`maubase help`" + ` or this project's own source over this file
where they disagree.

## Commands

- ` + "`maubase serve`" + ` — start the server (config via env vars; see .env.example)
- ` + "`maubase migrate new <name>`" + ` / ` + "`up`" + ` / ` + "`down [n]`" + ` / ` + "`redo [n]`" + ` / ` + "`to <ver>`" + ` / ` + "`status`" + ` / ` + "`diff`" + `
- ` + "`maubase version`" + `, ` + "`maubase help`" + `

## Schema changes always go through a migration

A migration file's SQL goes under a ` + "`-- +migrate Up`" + ` marker (an
optional ` + "`-- +migrate Down`" + ` section makes it revertible). Never edit
the live schema via raw SQL or the admin UI's SQL Studio
(` + "`/admin/ui/sql`" + `) without also writing a migration for it — that's
exactly the drift ` + "`maubase migrate diff`" + ` exists to catch. Run it
before considering schema work done; it exits non-zero if the live
database has tables/columns no migration explains, or vice versa.

## What this backend exposes

Every table created in a migration becomes a REST API automatically —
no route code to write:

- **Auth** (cookie session, a customer's own account): ` + "`POST /api/auth/signup`" + `,
  ` + "`POST /api/auth/login`" + `, ` + "`GET /api/auth/me`" + `, ` + "`POST /api/auth/logout`" + `,
  ` + "`GET /api/auth/me/export`" + `, ` + "`DELETE /api/auth/me`" + `.
- **Data — auto-REST** (` + "`GET`" + `/` + "`POST`" + `/` + "`PATCH`" + `/` + "`DELETE /api/data/{table}[/{id}]`" + `):
  requires a real OAuth access token — never the auth cookie above — with
  ` + "`records:read`" + ` (GET) or ` + "`records:write`" + ` (POST/PATCH/DELETE) scope; no
  anonymous access. A table with an ` + "`owner_id`" + ` column auto-scopes rows
  to whoever created them, and ` + "`owner_id`" + ` can never be set or changed
  by the client. Reserved/internal tables (including ` + "`_policies`" + `
  below) are never exposed this way.
- **Access rules beyond owner_id**: a ` + "`_policies`" + ` table (never itself
  exposed) can override the read/write default per table — e.g. public
  read, owner-only write. No rows there means today's owner_id-only
  default applies.
- **Storage**: ` + "`POST /api/storage/files`" + ` (multipart upload),
  ` + "`GET /api/storage/files`" + ` (list your own), ` + "`GET .../files/{id}`" + `
  (metadata) / ` + "`.../content`" + ` (bytes), ` + "`DELETE .../files/{id}`" + ` — scoped
  by ` + "`files:read`" + `/` + "`files:write`" + `, same OAuth-token model as data above.
- **Realtime**: ` + "`GET /api/realtime`" + ` upgrades to a WebSocket; subscribe
  per collection and get create/update/delete events, filtered to rows
  the connection's own token/policies would actually let it see.
- **OAuth 2.1** (where auto-REST/storage/realtime access tokens come
  from): ` + "`/oauth/register`" + ` (dynamic client registration),
  ` + "`/oauth/authorize`" + ` (login + consent), ` + "`/oauth/token`" + ` (PKCE code
  exchange, refresh), ` + "`/.well-known/oauth-authorization-server`" + `,
  ` + "`/.well-known/jwks.json`" + `.
- **Admin UI** (operating this deployment — not your app's own users):
  ` + "`/admin/ui/*`" + `, a separate owner-plane login/session, role-gated
  (viewer/admin+); JSON API at ` + "`/admin/auth`" + `, ` + "`/admin/owners`" + `,
  ` + "`/admin/audit-log`" + `, ` + "`/admin/maintenance`" + `.
<!-- maubase:end -->
`
