package main

import "strings"

// skillRelPath is where maubase init scaffolds the agent-context skill,
// relative to the project directory — see spec/project-init.md INIT-07.
// Nested under .claude/skills/ (Claude Code's own project-skill
// discovery path) rather than a root-level AGENTS.md/CLAUDE.md: those
// belong to whatever app gets built in this project, and maubase writing
// into a file it doesn't own risks clobbering it in an existing repo. A
// namespaced skill never competes for that.
const skillRelPath = ".claude/skills/maubase/SKILL.md"

// maubaseRepo is where this project's own spec/*.md lives — the
// authoritative, version-matched reference the skill points an agent
// to per topic. Deliberately a pointer, not inlined content: this
// project's tables/columns/access rules are discovered at runtime (a
// migration, the admin UI's create-table form, or SQL Studio can all
// add one after this file was generated) and a static file can't track
// that — see GET /api/schema below, which can. And restating spec/*.md
// as fresh prose here would just be documentation to keep in sync by
// hand forever, the exact failure mode this project's spec-first tests
// exist to avoid everywhere else.
const maubaseRepo = "Ucok23/maubase"

// renderSkill fills skillTemplate with the maubase version generating
// it, and with raw.githubusercontent.com links pinned to the exact
// commit or release tag that binary was built from (currentDocRef) —
// so every spec link resolves to the content this binary actually
// implements, not whatever "main" says by the time it's fetched.
func renderSkill() string {
	ref := currentDocRef()
	out := strings.ReplaceAll(skillTemplate, "{{VERSION}}", currentModuleVersion())
	out = strings.ReplaceAll(out, "{{DOCREF}}", ref)
	return out
}

// specURL builds a stable, directly-fetchable link to one spec file at
// ref — raw.githubusercontent.com rather than a github.com/.../blob/
// page, since the audience is an agent's fetch tool, not a browser: raw
// returns the plain markdown with no HTML chrome around it.
func specURL(ref, file string) string {
	return "https://raw.githubusercontent.com/" + maubaseRepo + "/" + ref + "/spec/" + file
}

// skillTemplate is wrapped in a <!-- maubase:begin/end --> managed
// block so a future "refresh this after upgrading" command (see #161)
// can replace just this content without touching anything a person
// appends below the closing marker.
//
// A var, not a const: it's built with specURL() calls baked in at
// program-init time (each one already carrying the literal "{{DOCREF}}"
// placeholder as its ref argument, replaced for real by renderSkill()),
// which Go's constant-expression rules don't allow in a const.
//
// Deliberately short. This is a pointer file, not a manual: every link
// below is either a live command (reflects this project's actual,
// current, possibly-just-changed state) or a spec file pinned to the
// exact commit that generated this — never prose restating either one,
// which would just be a second copy to keep in sync by hand.
var skillTemplate = `---
name: maubase
description: Use when working on a project backed by maubase (a self-hosted auth/database/storage/realtime backend) — adding endpoints, changing schema, or touching auth/migrations/access rules in this project.
---

<!-- maubase:begin {{VERSION}} -->
# maubase

This project's backend is maubase — self-hosted auth, a database with
an automatic REST API, file storage, realtime, and OAuth 2.1, on one
SQLite file. One ` + "`maubase serve`" + ` process serves exactly this project.

Generated by ` + "`maubase init`" + ` for **{{VERSION}}**. Below is either a live
command (this project's actual current state) or a spec link pinned to
the exact commit that generated this file — not prose written from
memory. Prefer both of those over training data or anything you might
otherwise recall about maubase's own source: neither is this project's
actual version, and both can simply be wrong for it.

## What actually exists in this project right now

Tables, columns, and access rules are created by a migration, the admin
UI's create-table form, or SQL Studio — all *after* this file was
generated, so nothing below describes them; ask the running server
instead:

- ` + "`GET /api/schema`" + ` — every collection ` + "`/api/data/*`" + ` exposes right
  now (columns, types, owner scoping, resolved read/write rules).
  Requires a ` + "`records:read`" + ` access token, and only exists at all when
  this project's ` + "`.env`" + ` sets ` + "`MAUBASE_ENV=development`" + ` — 404s
  otherwise. (` + specURL("{{DOCREF}}", "schema-introspection.md") + `)
- Not in development mode, or need history rather than current state:
  ` + "`maubase migrate status`" + ` plus ` + "`migrations/*.sql`" + `. Keep in mind the
  admin UI/SQL Studio can change the live schema without a matching
  migration file — ` + "`maubase migrate diff`" + ` catches that drift; run it
  before trusting migrations/ as a complete picture.

## What this backend's fixed API surface is — spec, not summary

- Auth (signup/login/session): ` + specURL("{{DOCREF}}", "identity.md") + `
- Auto-REST (` + "`/api/data/{table}`" + `): ` + specURL("{{DOCREF}}", "auto-rest.md") + `
- Access rules beyond owner_id (` + "`_policies`" + `): ` + specURL("{{DOCREF}}", "access-rules.md") + `
- Storage: ` + specURL("{{DOCREF}}", "storage.md") + `
- Realtime: ` + specURL("{{DOCREF}}", "realtime.md") + `
- OAuth 2.1 (where access tokens come from): ` + specURL("{{DOCREF}}", "oauth-token.md") + `
- Admin UI (` + "`/admin/ui/*`" + `, operating this deployment): ` + specURL("{{DOCREF}}", "admin-ui.md") + `
- Full index: ` + specURL("{{DOCREF}}", "README.md") + `

## Commands

` + "`maubase serve`" + `, ` + "`maubase migrate new/up/down/redo/to/status/diff`" + `, ` + "`maubase version`" + `

## The one rule with no exception

Never edit the live schema (raw SQL, admin UI create-table, SQL Studio)
without also writing a migration for it. Run ` + "`maubase migrate diff`" + `
before considering schema work done. Full migration workflow (new/up/
down/redo/to/status/diff, the Up/Down marker format, checksums):
` + specURL("{{DOCREF}}", "migrations-cli.md") + `
<!-- maubase:end -->
`
