// Package restapi is the auto-generated REST layer: every table in the
// database that isn't one of baas's own internal tables becomes a
// queryable/writable collection at /api/data/{table}, discovered by
// introspecting the schema rather than through any separate config —
// see the package's spec at spec/auto-rest.md for the exact behavior.
package restapi

import (
	"context"
	"database/sql"
	"fmt"
	"sort"
	"strings"
)

// OwnerColumnName is the one convention that turns a plain shared table
// into a per-user one: a table with a column by this name gets every row
// scoped to the access token's subject automatically (see handlers.go).
const OwnerColumnName = "owner_id"

// reservedTables are baas's own tables (see internal/db/migrations) —
// never exposed through auto-REST regardless of caller or token, so an
// access token can never end up querying sessions or OAuth client secrets
// through this layer.
var reservedTables = map[string]bool{
	"users": true, "sessions": true,
	"oauth_clients": true, "oauth_client_jti": true, "oauth_authorize_codes": true,
	"oauth_access_tokens": true, "oauth_refresh_tokens": true, "oauth_pkce_requests": true,
	"oauth_consents": true, "oauth_signing_keys": true, "oauth_hmac_secret": true,
	"owner_users": true, "owner_sessions": true, "owner_audit_log": true,
	"schema_migrations": true,
}

type Column struct {
	Name     string
	DeclType string
	NotNull  bool
	IsPK     bool
}

type Collection struct {
	Name    string
	Columns []Column

	// PKColumn is empty (and the table is not exposed) unless the table
	// has exactly one primary-key column — auto-REST doesn't support
	// composite keys in v1.
	PKColumn string
	// PKIsInteger is true for an INTEGER-affinity primary key, which
	// SQLite auto-assigns via rowid when omitted from an INSERT. A
	// non-integer (typically TEXT) primary key is instead generated by
	// this layer as a UUID if the client doesn't supply one.
	PKIsInteger bool

	// OwnerColumn is "" for a shared table, or OwnerColumnName for one
	// where every row is scoped to the token subject that created it.
	OwnerColumn string
}

func (c *Collection) HasColumn(name string) bool {
	for _, col := range c.Columns {
		if col.Name == name {
			return true
		}
	}
	return false
}

// Registry is the discovered set of exposed collections, built once at
// startup. Schema changes require a restart to pick up — auto-REST has no
// notion of "reload," matching how migrations already work.
type Registry struct {
	collections map[string]*Collection
}

func (r *Registry) Get(name string) (*Collection, bool) {
	c, ok := r.collections[name]
	return c, ok
}

// ownedCollections returns every registered collection with row-level
// ownership (i.e. an owner_id column), sorted by name for deterministic
// iteration — used by account export/erasure, where output order and
// delete order should be stable and not depend on Go's map iteration.
func (r *Registry) ownedCollections() []*Collection {
	var out []*Collection
	for _, c := range r.collections {
		if c.OwnerColumn != "" {
			out = append(out, c)
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

// Discover introspects the database's actual schema (via sqlite_master
// and PRAGMA table_info) and returns every table eligible to be exposed:
// not reserved, and with exactly one primary-key column.
func Discover(ctx context.Context, db *sql.DB) (*Registry, error) {
	rows, err := db.QueryContext(ctx, `SELECT name FROM sqlite_master WHERE type = 'table'`)
	if err != nil {
		return nil, fmt.Errorf("list tables: %w", err)
	}
	var tableNames []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			rows.Close()
			return nil, err
		}
		tableNames = append(tableNames, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	rows.Close()

	reg := &Registry{collections: map[string]*Collection{}}
	for _, name := range tableNames {
		if isReserved(name) {
			continue
		}
		col, err := describeTable(ctx, db, name)
		if err != nil {
			return nil, fmt.Errorf("describe table %s: %w", name, err)
		}
		if col.PKColumn == "" {
			// No single-column primary key: not exposed. A table with no
			// PK, or a composite one, can't be addressed at /{id}.
			continue
		}
		reg.collections[name] = col
	}
	return reg, nil
}

func isReserved(name string) bool {
	return strings.HasPrefix(name, "sqlite_") || reservedTables[name]
}

func describeTable(ctx context.Context, db *sql.DB, name string) (*Collection, error) {
	rows, err := db.QueryContext(ctx, fmt.Sprintf(`PRAGMA table_info(%s)`, quoteIdent(name)))
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	col := &Collection{Name: name}
	var pkCols []Column
	for rows.Next() {
		var cid, notNull, pk int
		var colName, declType string
		var dfltValue any
		if err := rows.Scan(&cid, &colName, &declType, &notNull, &dfltValue, &pk); err != nil {
			return nil, err
		}
		c := Column{Name: colName, DeclType: declType, NotNull: notNull != 0, IsPK: pk != 0}
		col.Columns = append(col.Columns, c)
		if c.IsPK {
			pkCols = append(pkCols, c)
		}
		if colName == OwnerColumnName {
			col.OwnerColumn = OwnerColumnName
		}
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	if len(pkCols) == 1 {
		col.PKColumn = pkCols[0].Name
		col.PKIsInteger = strings.Contains(strings.ToUpper(pkCols[0].DeclType), "INT")
	}
	return col, nil
}

// quoteIdent double-quotes a SQL identifier for safe interpolation.
// Table/column names here always come from our own schema introspection
// (chosen by whoever writes migrations — the deployment owner, a trusted
// party), never directly from an HTTP request, but every identifier
// that ends up in a query string still goes through this rather than
// being trusted as pre-safe.
func quoteIdent(name string) string {
	return `"` + strings.ReplaceAll(name, `"`, `""`) + `"`
}
