// Package restapi is the auto-generated REST layer: every table in the
// database that isn't one of maubase's own internal tables becomes a
// queryable/writable collection at /api/data/{table}, discovered by
// introspecting the schema rather than through any separate config —
// see the package's spec at spec/auto-rest.md for the exact behavior.
package restapi

import (
	"context"
	"database/sql"
	"fmt"
	"sort"
	"strings"
)

// OwnerColumnName is the one convention that turns a plain shared table
// into a per-user one: a table with a column by this name gets every row
// scoped to the access token's subject automatically (see handlers.go).
const OwnerColumnName = "owner_id"

// reservedTables are maubase's own tables (see internal/db/migrations) —
// never exposed through auto-REST regardless of caller or token, so an
// access token can never end up querying sessions or OAuth client secrets
// through this layer.
//
// SECURITY: this list must be kept in sync with every table
// internal/db/migrations creates, by hand, every time a migration adds
// one — there is no structural mechanism forcing that (see
// TestRestAPI_NoAppSchemaExposesNothing in test/restapi_test.go, which
// exists specifically to catch the day this list is forgotten again:
// it fails loudly if maubase's own migrations ever produce a table this
// map doesn't know about, rather than silently exposing it). Two tables
// — password_reset_tokens, social_identities (migrations 0007/0008) —
// shipped without being added here, and were exposed as ordinary
// shared collections at /api/data/password_reset_tokens and
// /api/data/social_identities to any caller holding a routine
// records:write token: readable (a full account-enumeration/PII leak:
// every user_id, email, and reset-token hash in the deployment) and
// writable (an attacker could POST a forged password_reset_tokens row
// naming any victim's real user_id and a token hash of their own
// choosing, then redeem it via the real POST /api/auth/reset-password
// — a complete, unauthenticated-relative-to-the-victim account
// takeover). Fixed here; see the git history for the incident.
var reservedTables = map[string]bool{
	"users": true, "sessions": true,
	"oauth_clients": true, "oauth_client_jti": true, "oauth_authorize_codes": true,
	"oauth_access_tokens": true, "oauth_refresh_tokens": true, "oauth_pkce_requests": true,
	"oauth_consents": true, "oauth_signing_keys": true, "oauth_hmac_secret": true,
	"owner_users": true, "owner_sessions": true, "owner_audit_log": true,
	"schema_migrations":     true,
	"files":                 true,
	"_policies":             true,
	"password_reset_tokens": true,
	"social_identities":     true,
}

// Rule is one of a closed vocabulary of per-operation access rules a
// collection can have — see spec/access-rules.md.
type Rule string

const (
	// RuleOwner restricts an operation to the row's own owner_id.
	// Requires the collection to have an OwnerColumn.
	RuleOwner Rule = "owner"
	// RuleShared allows any caller with the operation's scope,
	// unfiltered by row.
	RuleShared Rule = "shared"
	// RuleDenied turns an operation off for a collection entirely,
	// through this API, regardless of caller or scope.
	RuleDenied Rule = "denied"
)

// Operation names as stored in the _policies table.
const (
	OpRead   = "read"
	OpCreate = "create"
	OpUpdate = "update"
	OpDelete = "delete"
)

type Column struct {
	Name     string
	DeclType string
	NotNull  bool
	IsPK     bool
}

type Collection struct {
	Name    string
	Columns []Column

	// PKColumn is empty (and the table is not exposed) unless the table
	// has exactly one primary-key column — auto-REST doesn't support
	// composite keys in v1.
	PKColumn string
	// PKIsInteger is true for an INTEGER-affinity primary key, which
	// SQLite auto-assigns via rowid when omitted from an INSERT. A
	// non-integer (typically TEXT) primary key is instead generated by
	// this layer as a UUID if the client doesn't supply one.
	PKIsInteger bool

	// OwnerColumn is "" for a shared table, or OwnerColumnName for one
	// where every row is scoped to the token subject that created it.
	OwnerColumn string

	// ReadRule/CreateRule/UpdateRule/DeleteRule are this collection's
	// effective per-operation access rule: RuleOwner if OwnerColumn is
	// set, RuleShared otherwise, unless overridden by a row in
	// _policies — see spec/access-rules.md. Read covers both list and
	// get-by-id.
	ReadRule, CreateRule, UpdateRule, DeleteRule Rule
}

func (c *Collection) HasColumn(name string) bool {
	for _, col := range c.Columns {
		if col.Name == name {
			return true
		}
	}
	return false
}

// Registry is the discovered set of exposed collections, built once at
// startup. Schema changes require a restart to pick up — auto-REST has no
// notion of "reload," matching how migrations already work.
type Registry struct {
	collections map[string]*Collection
}

func (r *Registry) Get(name string) (*Collection, bool) {
	c, ok := r.collections[name]
	return c, ok
}

// All returns every exposed collection, sorted by name — used by the
// embedded admin UI's data browser (spec/admin-ui.md ADMINUI-11).
func (r *Registry) All() []*Collection {
	out := make([]*Collection, 0, len(r.collections))
	for _, c := range r.collections {
		out = append(out, c)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

// ownedCollections returns every registered collection with row-level
// ownership (i.e. an owner_id column), sorted by name for deterministic
// iteration — used by account export/erasure, where output order and
// delete order should be stable and not depend on Go's map iteration.
func (r *Registry) ownedCollections() []*Collection {
	var out []*Collection
	for _, c := range r.collections {
		if c.OwnerColumn != "" {
			out = append(out, c)
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

// Discover introspects the database's actual schema (via sqlite_master
// and PRAGMA table_info) and returns every table eligible to be exposed:
// not reserved, and with exactly one primary-key column. Every
// collection's default per-operation access rule is set from whether it
// has an owner_id column, then any override declared in _policies is
// applied on top — see applyPolicies and spec/access-rules.md.
func Discover(ctx context.Context, db *sql.DB) (*Registry, error) {
	rows, err := db.QueryContext(ctx, `SELECT name FROM sqlite_master WHERE type = 'table'`)
	if err != nil {
		return nil, fmt.Errorf("list tables: %w", err)
	}
	var tableNames []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			rows.Close()
			return nil, err
		}
		tableNames = append(tableNames, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	rows.Close()

	reg := &Registry{collections: map[string]*Collection{}}
	for _, name := range tableNames {
		if isReserved(name) {
			continue
		}
		col, err := describeTable(ctx, db, name)
		if err != nil {
			return nil, fmt.Errorf("describe table %s: %w", name, err)
		}
		if col.PKColumn == "" {
			// No single-column primary key: not exposed. A table with no
			// PK, or a composite one, can't be addressed at /{id}.
			continue
		}
		def := RuleShared
		if col.OwnerColumn != "" {
			def = RuleOwner
		}
		col.ReadRule, col.CreateRule, col.UpdateRule, col.DeleteRule = def, def, def, def
		reg.collections[name] = col
	}

	if err := applyPolicies(ctx, db, reg); err != nil {
		return nil, err
	}
	return reg, nil
}

// applyPolicies overrides each named collection's default rule for each
// (collection, operation) row found in _policies. A row naming a
// collection Discover didn't expose (unknown, reserved, or no
// single-column PK), an unrecognized operation, or a RuleOwner override
// on a collection with no owner_id column (spec/access-rules.md
// ACCESS-08) fails the whole call — a deployment's own migrations are a
// trusted, deliberate configuration, so a mistake here should stop
// startup loudly rather than silently apply nothing.
func applyPolicies(ctx context.Context, db *sql.DB, reg *Registry) error {
	rows, err := db.QueryContext(ctx, `SELECT collection, operation, rule FROM _policies`)
	if err != nil {
		return fmt.Errorf("list access policies: %w", err)
	}
	defer rows.Close()

	for rows.Next() {
		var collection, operation, rule string
		if err := rows.Scan(&collection, &operation, &rule); err != nil {
			return fmt.Errorf("scan access policy: %w", err)
		}
		col, ok := reg.collections[collection]
		if !ok {
			return fmt.Errorf("_policies: %s.%s: no such exposed collection", collection, operation)
		}
		r := Rule(rule)
		if r == RuleOwner && col.OwnerColumn == "" {
			return fmt.Errorf("_policies: %s.%s: rule %q requires an %s column, but %s has none",
				collection, operation, RuleOwner, OwnerColumnName, collection)
		}
		switch operation {
		case OpRead:
			col.ReadRule = r
		case OpCreate:
			col.CreateRule = r
		case OpUpdate:
			col.UpdateRule = r
		case OpDelete:
			col.DeleteRule = r
		default:
			return fmt.Errorf("_policies: %s: unknown operation %q", collection, operation)
		}
	}
	return rows.Err()
}

func isReserved(name string) bool {
	return strings.HasPrefix(name, "sqlite_") || reservedTables[name]
}

// columnAffinity implements SQLite's column type affinity rules (see
// https://www.sqlite.org/datatype3.html#determination_of_column_affinity)
// closely enough to distinguish TEXT affinity, where a value is stored
// exactly as given, from the numeric affinities (INTEGER, REAL, and the
// NUMERIC catch-all) that will coerce a canonical-looking numeric string
// into a number before storing or comparing it. BLOB affinity (a declared
// type containing "BLOB", or no declared type at all) is also
// coercion-free, but isn't this codebase's convention for any column, so
// callers checking for TEXT affinity specifically treat it the same as a
// numeric affinity: not what owner_id is supposed to be.
func columnAffinity(declType string) string {
	t := strings.ToUpper(declType)
	switch {
	case strings.Contains(t, "INT"):
		return "INTEGER"
	case strings.Contains(t, "CHAR"), strings.Contains(t, "CLOB"), strings.Contains(t, "TEXT"):
		return "TEXT"
	case strings.Contains(t, "BLOB"), t == "":
		return "BLOB"
	case strings.Contains(t, "REAL"), strings.Contains(t, "FLOA"), strings.Contains(t, "DOUB"):
		return "REAL"
	default:
		return "NUMERIC"
	}
}

func describeTable(ctx context.Context, db *sql.DB, name string) (*Collection, error) {
	rows, err := db.QueryContext(ctx, fmt.Sprintf(`PRAGMA table_info(%s)`, quoteIdent(name)))
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	col := &Collection{Name: name}
	var pkCols []Column
	for rows.Next() {
		var cid, notNull, pk int
		var colName, declType string
		var dfltValue any
		if err := rows.Scan(&cid, &colName, &declType, &notNull, &dfltValue, &pk); err != nil {
			return nil, err
		}
		c := Column{Name: colName, DeclType: declType, NotNull: notNull != 0, IsPK: pk != 0}
		col.Columns = append(col.Columns, c)
		if c.IsPK {
			pkCols = append(pkCols, c)
		}
		if colName == OwnerColumnName {
			if aff := columnAffinity(declType); aff != "TEXT" {
				return nil, fmt.Errorf("%s.owner_id has declared type %q (%s affinity), but owner_id must have TEXT affinity: a numeric affinity lets SQLite silently coerce differently-formatted owner values (e.g. \"7\", \"07\", and \"7.0\") into the same stored value, so distinct subjects could end up scoped to the same rows — declare it as owner_id TEXT NOT NULL instead", name, declType, aff)
			}
			col.OwnerColumn = OwnerColumnName
		}
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	if len(pkCols) == 1 {
		col.PKColumn = pkCols[0].Name
		col.PKIsInteger = strings.Contains(strings.ToUpper(pkCols[0].DeclType), "INT")
	}
	return col, nil
}

// quoteIdent double-quotes a SQL identifier for safe interpolation.
// Table/column names here always come from our own schema introspection
// (chosen by whoever writes migrations — the deployment owner, a trusted
// party), never directly from an HTTP request, but every identifier
// that ends up in a query string still goes through this rather than
// being trusted as pre-safe.
func quoteIdent(name string) string {
	return `"` + strings.ReplaceAll(name, `"`, `""`) + `"`
}
